## SET PATH
export MONGODB='/c/Program Files/MongoDB/Server'
export PATH=$MONGODB/mongosh/bin:$PATH

# generated by Git for Windows
ccvid(){ 
  cd "/c/Data/OneDrive - Bildungszentrum Zürichsee/videos/Cloudcomputing/"
}
bivo() { 
  cd '/c/Data/OneDrive - Bildungszentrum Zürichsee/workspace/wp_modulentwicklung/BIVO_2021/'
}
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
